name: Test 
on:
  workflow_dispatch:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.YOY }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://${{ secrets.IP }}/'
          allow_issue_writing: false
          cmd_options: '-j'
