name: Test 
on: workflow_dispatch
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.YOY }}
          target: 'https://${{ secrets.IP }}/'
          allow_issue_writing: false
          cmd_options: '-j'
